bot:
  name: ${BOT_NAME}
  token: ${BOT_TOKEN}
  devChatId: ${DEV_CHATID}
  resources:
    greeting: "target/greeting.txt"
    questions: "target/questions.json"

spring:
  datasource:
    url: ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
    driverClassName: org.postgresql.Driver
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
