bot:
  name: ${BOT_NAME}
  token: ${BOT_TOKEN}
  devChatId: ${DEV_CHATID}
  resources:
    greeting: "target/classes/greeting.txt"
    questions: "target/classes/questions.json"
    image: "target/classes/compass.png"
    social-url: "https://docs.google.com/forms/d/e/1FAIpQLSfaHGyZ_gWNPMl0JMDPjLRvXdRorHadNAJSXEglSmGGu1G95A/viewform?usp=pp_url&entry.1626607362="

spring:
  datasource:
    url: ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
    driverClassName: org.postgresql.Driver
  jpa:
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
